### PR TITLE
Rename repository to govuk-frontend-jinja

### PR DESCRIPTION
**Pull request by risicle**
https://trello.com/c/FKXvq2kd/

I could have gone with `govuk-frontend-jinja2` which would have technically been more accurate, but it wouldn't have been totally clear to the uninitiated which component the `2` referred to.

### CODE REVIEW

**Comment by lfdebrux** [comment]
Are the peeps on the Design System okay with this name?

**Comment by risicle** [comment]
> Are the peeps on the Design System okay with this name?

@36degrees - thoughts? The reasoning for the rename is that there are lots of templating systems used in python and this repo really does just concern itself with jinja.

**Comment by risicle** [comment]
I asked him offline - he's fine with the jinja part of it and probably the name in general, though he mentions that it might be good to be careful about how official we make the package sound in the readme.

**Comment by lfdebrux** [comment]
@risicle cool. Agreed, a disclaimer would be a good idea, perhaps something saying that if you want support don't go to GOV.UK.

**Comment by lfdebrux** [comment]
As well as changing the repo and distributable package name we should change the importable package name, or make it a namespace package.

**Comment by risicle** [comment]
Yeah sure.

**Comment by lfdebrux** [comment]
I've added a disclaimer, are you guys okay with this @36degrees?

**Comment by risicle** [comment]
How long's this going to sit here needing continual rebasing?

**Comment by lfdebrux** [comment]
@risicle Ah, I thought I couldn't approve as I made commits, but it looks like I can

**Pull request merged**
